import Head from 'next/head'
import Navbar from '../../components/Navbar'
import { prisma } from '../lib/prisma'

export async function getServerSideProps (context) {
    const {id} = context.params
    const posts = await prisma.bandPost.findUnique({
        where: { id: parseInt(id) },
        include: {
        author: {
            select: { name: true },
        },
        },
    });
    console.log(posts)
    return {
        props: posts,
    };
};

export default function Home(props) {
    return (
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar/>
        <main>
          <div key={props.id}>
            <h2>{props.author.name}</h2>
            <div>{props.description}</div>
          </div>
        </main>
        <footer>
        </footer>
      </div>
    )
  }
  