import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import { gql, useQuery, useMutation } from '@apollo/client'


const AllBandPostsQuery = gql`
  query allLinksQuery($first: Int, $after: String) {
    bandPosts(first: $first, after: $after) {
      pageInfo {
        endCursor
        hasNextPage
      }
      edges {
        cursor
        node {
          imageUrl
          title
          tags
          content
          id
        }
      }
    }
  }
`;

export default function Home() {
  const { data, loading, error, fetchMore } = useQuery(AllBandPostsQuery, {
    variables: { first: 2 },
  });

  if (loading) return <p>Loading...</p>
  if (error) return <p>Oh no... {error.message}</p>

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <main>
      <div className="container mx-auto max-w-5xl my-20">
        <ul className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
          {data.bandPosts.map(link => (
            <li key={link.id} className="shadow  max-w-md  rounded">
              <Image alt='image' className="shadow-sm" src={link.imageUrl}/>
              <div className="p-5 flex flex-col space-y-2">
                <p className="text-sm text-blue-500">{link.tags}</p>
                <p className="text-lg font-medium">{link.title}</p>
                <p className="text-gray-600">{link.content}</p>
              </div>
            </li>
          ))}
        </ul>
      </div>
      </main>
      <footer>
      </footer>
    </div>
  )
}
