import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import { gql, useQuery, useMutation, InMemoryCache } from '@apollo/client'
import { offsetLimitPagination } from "@apollo/client/utilities";
import Pagination from "@choc-ui/paginator";
import { Flex, useColorModeValue } from "@chakra-ui/react";


export default function Home() {
  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <main>
      </main>
      <footer>
      </footer>
    </div>
  )
}
